Parameters:
  VpcId:
    Type: String
  Subnet1Id:
    Type: String
  Subnet2Id:
    Type: String

Resources:
  PostgresSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Postgres recovery database
      SubnetIds:
        - !Ref Subnet1Id
        - !Ref Subnet2Id
      Tags:
        - Key: Name
          Value: PostgresSubnetGroup
  PostgresSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Postgres database
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: PostgresSecurityGroup
  PostgresDatabaseRecovery:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: PostgresDatabaseRecovery
      AllocatedStorage: '20'
      DBInstanceClass: db.c6gd.medium
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: password
      BackupRetentionPeriod: 7
      MultiAZ: true
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref PostgresSubnetGroup
      VPCSecurityGroups:
        - !Ref PostgresSecurityGroup
