Parameters:
  VpcId:
    Type: String
  Subnet1Id:
    Type: String
  Subnet2Id:
    Type: String

Resources:
  EksSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EKS cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EksSecurityGroup
  EksCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: atheon
      Version: "1.30"
      RoleArn: "arn:aws:iam::739337767874:role/LabRole"
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksSecurityGroup 
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
  EksFargateProfile:
    Type: AWS::EKS::FargateProfile
    Properties:
      FargateProfileName: prod-node-pool
      ClusterName: !Ref EksCluster
      PodExecutionRoleArn: "arn:aws:iam::739337767874:role/LabRole"
      Subnets:
        - !Ref Subnet1Id
        - !Ref Subnet2Id
      Selectors:
        - Namespace: prod-us
