Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cff-minispace-bucket/network.formation.yaml
  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cff-minispace-bucket/rds.formation.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        Subnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1a
        Subnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1b
  EksStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cff-minispace-bucket/eks.formation.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        Subnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1a
        Subnet2Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1b
