Parameters:
  Subnet1Id:
    Type: String
  Subnet2Id:
    Type: String

Resources:
  ElasticIp1a:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: Name
          Value: ElasticIp1a
  ElasticIp1b:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: Name
          Value: ElasticIp1b
  NatGateway1a:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref Subnet1Id
      AllocationId: !GetAtt ElasticIp1a.AllocationId
      Tags:
        - Key: Name
          Value: NatGateway1a
  NatGateway1b:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref Subnet2Id
      AllocationId: !GetAtt ElasticIp1b.AllocationId
      Tags:
        - Key: Name
          Value: NatGateway1b

Outputs:
  NatGateway1aId:
    Value: !Ref NatGateway1a
  NatGateway1bId:
    Value: !Ref NatGateway1b