Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: minispace-photoss
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketId:
    Value: !Ref Bucket
  BucketDomainName:
    Value: !GetAtt Bucket.DomainName
  BucketName:
    Value: minispace-photoss